### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by JosephTLockwood** [IOdissey/maytag#1]
Hello I am just starting to get into April Tag tracking. I have started been comparing different methods of April Tag tracking located [here](https://colab.research.google.com/drive/1M9ZATXedaSMWxmF00T3nvJOV3b2YMVKr?usp=sharing). I was wondering if you will have a python wrapper or way to run it in python. I would love to see how this compares speed wise to the other methods in my test.

**Comment by IOdissey** [comment]
Hello. I'm sorry for answering late.
While I do not plan to make a python wrapper. I love c++ :)
